name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [ '2.11', '2.12' ]
        spark: [ '2.4.2', '2.4.5', '3.0.0-preview2' ]
        include:
          - scala: '2.11'
            spark: '3.0.0-preview2'
            skip: true
    name: Build Spark with Scala ${{ matrix.scala }} / Spark ${{ matrix.spark }}
    if: '!matrix.skip'

    steps:
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository/com
          key: ${{ matrix.scala }}-${{ matrix.spark }}-maven-com-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ matrix.scala }}-${{ matrix.spark }}-maven-com-
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository/org
          key: ${{ matrix.scala }}-${{ matrix.spark }}-maven-org-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ matrix.scala }}-${{ matrix.spark }}-maven-org-
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        if: "${{ matrix.spark }} != '3.0.0-preview2' && ${{ matrix.scala }} != '2.11'"
        run: |
          export MAVEN_OPTS="-Xmx2g -XX:ReservedCodeCacheSize=512m -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN"
          export MAVEN_CLI_OPTS="-B --no-transfer-progress"
          mvn $MAVEN_CLI_OPTS -Pscala-${{ matrix.scala }} -Dspark.version=${{ matrix.spark }} clean verify
          rm -rf ~/.m2/repository/org/apache/spark

